# Site settings
title: Brad Johnson
email: BradJohnson@mailbox.org
url: http://phoenixlandpirate.github,io
description: "براد جونسون" 
description2: "طائر العنقاء 土地Пират"
lp-bg: /img/mwm-x2.jpg
og-image: /img/og-large.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-light: '#222222'
  links: '#219ab3'
  text-on-black: '#858585'

# Footer settings
footer: Brad Johnson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Telegram
    url: https://t.me/PhoenixLandPirate
  - title2: Matrix
    url: https://matrix.to/#/@phoenixlandpirate:halogen.city


# Build settings
markdown: kramdown
permalink: pretty
